apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "admin.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ template "admin.fullname" . }}
spec:
#  clusterIP: None
  ports:
  - name: "site"
    port: 80
    targetPort: 80
  selector:
    app: {{ template "admin.fullname" . }}
status:
  loadBalancer: {}

